../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/  proto/http_server.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/  proto/baidu_realtime_bidding.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/black_list_info.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/business_ad.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/idea_info.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/phrase_business.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/plan_info.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/stop_word.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/unit_idea.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/unit_info.proto
../../third-64/protobuf/bin/protoc --cpp_out=./proto/ -I=proto/ -I=../../app/ecom/im/xbuiltin/output/include/ -I=../../third-64/protobuf/include/ --plugin=protoc-gen-xbuiltin=../../app/ecom/im/xbuiltin/output/bin/xbuiltin-generator --xbuiltin_out ./proto/ proto/user_info.proto
