// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unit_info.proto

#ifndef PROTOBUF_unit_5finfo_2eproto__INCLUDED
#define PROTOBUF_unit_5finfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "xbuiltin-options.pb.h"
#include <xbuiltin/Utils.h>
// @@protoc_insertion_point(includes)

namespace ad {
namespace rtb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_unit_5finfo_2eproto();
void protobuf_AssignDesc_unit_5finfo_2eproto();
void protobuf_ShutdownFile_unit_5finfo_2eproto();

class unit_info;

// ===================================================================

class unit_info : public ::google::protobuf::Message {
 public:
  unit_info();
  virtual ~unit_info();
  
  unit_info(const unit_info& from);
  
  inline unit_info& operator=(const unit_info& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const unit_info& default_instance();
  
  void Swap(unit_info* other);
  
  // implements Message ----------------------------------------------
  
  unit_info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const unit_info& from);
  void MergeFrom(const unit_info& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint64 level = 1;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 1;
  inline ::google::protobuf::uint64 level() const;
  inline void set_level(::google::protobuf::uint64 value);
  
  // required uint64 unitid = 2;
  inline bool has_unitid() const;
  inline void clear_unitid();
  static const int kUnitidFieldNumber = 2;
  inline ::google::protobuf::uint64 unitid() const;
  inline void set_unitid(::google::protobuf::uint64 value);
  
  // required uint64 planid = 3;
  inline bool has_planid() const;
  inline void clear_planid();
  static const int kPlanidFieldNumber = 3;
  inline ::google::protobuf::uint64 planid() const;
  inline void set_planid(::google::protobuf::uint64 value);
  
  // required uint64 userid = 4;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUseridFieldNumber = 4;
  inline ::google::protobuf::uint64 userid() const;
  inline void set_userid(::google::protobuf::uint64 value);
  
  // required uint64 unitbid = 5;
  inline bool has_unitbid() const;
  inline void clear_unitbid();
  static const int kUnitbidFieldNumber = 5;
  inline ::google::protobuf::uint64 unitbid() const;
  inline void set_unitbid(::google::protobuf::uint64 value);
  
  // optional bytes negative = 6;
  inline bool has_negative() const;
  inline void clear_negative();
  static const int kNegativeFieldNumber = 6;
  inline const ::std::string& negative() const;
  inline void set_negative(const ::std::string& value);
  inline void set_negative(const char* value);
  inline void set_negative(const void* value, size_t size);
  inline ::std::string* mutable_negative();
  inline ::std::string* release_negative();
  
  // optional bytes exactnegative = 7;
  inline bool has_exactnegative() const;
  inline void clear_exactnegative();
  static const int kExactnegativeFieldNumber = 7;
  inline const ::std::string& exactnegative() const;
  inline void set_exactnegative(const ::std::string& value);
  inline void set_exactnegative(const char* value);
  inline void set_exactnegative(const void* value, size_t size);
  inline ::std::string* mutable_exactnegative();
  inline ::std::string* release_exactnegative();
  
  // required bytes name = 8;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 8;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // required bytes cdate = 9;
  inline bool has_cdate() const;
  inline void clear_cdate();
  static const int kCdateFieldNumber = 9;
  inline const ::std::string& cdate() const;
  inline void set_cdate(const ::std::string& value);
  inline void set_cdate(const char* value);
  inline void set_cdate(const void* value, size_t size);
  inline ::std::string* mutable_cdate();
  inline ::std::string* release_cdate();
  
  // required bytes udate = 10;
  inline bool has_udate() const;
  inline void clear_udate();
  static const int kUdateFieldNumber = 10;
  inline const ::std::string& udate() const;
  inline void set_udate(const ::std::string& value);
  inline void set_udate(const char* value);
  inline void set_udate(const void* value, size_t size);
  inline ::std::string* mutable_udate();
  inline ::std::string* release_udate();
  
  static inline int generate_keysign(const uint64_t xdict_unitid, uint64_t *output) {
    if (::xbuiltin::make_sign64(xdict_unitid, output) < 0) {
      return -1;
    }
    return 0;
  }
  int generate_keysign(uint64_t *output) {
    return generate_keysign(unitid(), output);
  }
  void clear_optionals() {
  }
  int load_tsl(char *&str) {
    // level
    uint64_t xdict_level_value;
    if (::xbuiltin::xconvert(str, &xdict_level_value) < 0) {
      return -1;
    }
    set_level(xdict_level_value);
    // unitid
    uint64_t xdict_unitid_value;
    if (::xbuiltin::xconvert(str, &xdict_unitid_value) < 0) {
      return -1;
    }
    set_unitid(xdict_unitid_value);
    // planid
    uint64_t xdict_planid_value;
    if (::xbuiltin::xconvert(str, &xdict_planid_value) < 0) {
      return -1;
    }
    set_planid(xdict_planid_value);
    // userid
    uint64_t xdict_userid_value;
    if (::xbuiltin::xconvert(str, &xdict_userid_value) < 0) {
      return -1;
    }
    set_userid(xdict_userid_value);
    // unitbid
    uint64_t xdict_unitbid_value;
    if (::xbuiltin::xconvert(str, &xdict_unitbid_value) < 0) {
      return -1;
    }
    set_unitbid(xdict_unitbid_value);
    // negative
    char * xdict_negative_value;
    if (::xbuiltin::xconvert(str, &xdict_negative_value) < 0) {
      return -1;
    }
    set_negative(xdict_negative_value);
    // exactnegative
    char * xdict_exactnegative_value;
    if (::xbuiltin::xconvert(str, &xdict_exactnegative_value) < 0) {
      return -1;
    }
    set_exactnegative(xdict_exactnegative_value);
    // name
    char * xdict_name_value;
    if (::xbuiltin::xconvert(str, &xdict_name_value) < 0) {
      return -1;
    }
    set_name(xdict_name_value);
    // cdate
    char * xdict_cdate_value;
    if (::xbuiltin::xconvert(str, &xdict_cdate_value) < 0) {
      return -1;
    }
    set_cdate(xdict_cdate_value);
    // udate
    char * xdict_udate_value;
    if (::xbuiltin::xconvert(str, &xdict_udate_value) < 0) {
      return -1;
    }
    set_udate(xdict_udate_value);
    return 0;
  }
  // @@protoc_insertion_point(class_scope:ad.rtb.unit_info)
 private:
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_unitid();
  inline void clear_has_unitid();
  inline void set_has_planid();
  inline void clear_has_planid();
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_unitbid();
  inline void clear_has_unitbid();
  inline void set_has_negative();
  inline void clear_has_negative();
  inline void set_has_exactnegative();
  inline void clear_has_exactnegative();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_cdate();
  inline void clear_has_cdate();
  inline void set_has_udate();
  inline void clear_has_udate();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 level_;
  ::google::protobuf::uint64 unitid_;
  ::google::protobuf::uint64 planid_;
  ::google::protobuf::uint64 userid_;
  ::google::protobuf::uint64 unitbid_;
  ::std::string* negative_;
  ::std::string* exactnegative_;
  ::std::string* name_;
  ::std::string* cdate_;
  ::std::string* udate_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_unit_5finfo_2eproto();
  friend void protobuf_AssignDesc_unit_5finfo_2eproto();
  friend void protobuf_ShutdownFile_unit_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static unit_info* default_instance_;
};
// ===================================================================


// ===================================================================

// unit_info

// optional uint64 level = 1;
inline bool unit_info::has_level() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void unit_info::set_has_level() {
  _has_bits_[0] |= 0x00000001u;
}
inline void unit_info::clear_has_level() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void unit_info::clear_level() {
  level_ = GOOGLE_ULONGLONG(0);
  clear_has_level();
}
inline ::google::protobuf::uint64 unit_info::level() const {
  return level_;
}
inline void unit_info::set_level(::google::protobuf::uint64 value) {
  set_has_level();
  level_ = value;
}

// required uint64 unitid = 2;
inline bool unit_info::has_unitid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void unit_info::set_has_unitid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void unit_info::clear_has_unitid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void unit_info::clear_unitid() {
  unitid_ = GOOGLE_ULONGLONG(0);
  clear_has_unitid();
}
inline ::google::protobuf::uint64 unit_info::unitid() const {
  return unitid_;
}
inline void unit_info::set_unitid(::google::protobuf::uint64 value) {
  set_has_unitid();
  unitid_ = value;
}

// required uint64 planid = 3;
inline bool unit_info::has_planid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void unit_info::set_has_planid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void unit_info::clear_has_planid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void unit_info::clear_planid() {
  planid_ = GOOGLE_ULONGLONG(0);
  clear_has_planid();
}
inline ::google::protobuf::uint64 unit_info::planid() const {
  return planid_;
}
inline void unit_info::set_planid(::google::protobuf::uint64 value) {
  set_has_planid();
  planid_ = value;
}

// required uint64 userid = 4;
inline bool unit_info::has_userid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void unit_info::set_has_userid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void unit_info::clear_has_userid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void unit_info::clear_userid() {
  userid_ = GOOGLE_ULONGLONG(0);
  clear_has_userid();
}
inline ::google::protobuf::uint64 unit_info::userid() const {
  return userid_;
}
inline void unit_info::set_userid(::google::protobuf::uint64 value) {
  set_has_userid();
  userid_ = value;
}

// required uint64 unitbid = 5;
inline bool unit_info::has_unitbid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void unit_info::set_has_unitbid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void unit_info::clear_has_unitbid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void unit_info::clear_unitbid() {
  unitbid_ = GOOGLE_ULONGLONG(0);
  clear_has_unitbid();
}
inline ::google::protobuf::uint64 unit_info::unitbid() const {
  return unitbid_;
}
inline void unit_info::set_unitbid(::google::protobuf::uint64 value) {
  set_has_unitbid();
  unitbid_ = value;
}

// optional bytes negative = 6;
inline bool unit_info::has_negative() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void unit_info::set_has_negative() {
  _has_bits_[0] |= 0x00000020u;
}
inline void unit_info::clear_has_negative() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void unit_info::clear_negative() {
  if (negative_ != &::google::protobuf::internal::kEmptyString) {
    negative_->clear();
  }
  clear_has_negative();
}
inline const ::std::string& unit_info::negative() const {
  return *negative_;
}
inline void unit_info::set_negative(const ::std::string& value) {
  set_has_negative();
  if (negative_ == &::google::protobuf::internal::kEmptyString) {
    negative_ = new ::std::string;
  }
  negative_->assign(value);
}
inline void unit_info::set_negative(const char* value) {
  set_has_negative();
  if (negative_ == &::google::protobuf::internal::kEmptyString) {
    negative_ = new ::std::string;
  }
  negative_->assign(value);
}
inline void unit_info::set_negative(const void* value, size_t size) {
  set_has_negative();
  if (negative_ == &::google::protobuf::internal::kEmptyString) {
    negative_ = new ::std::string;
  }
  negative_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* unit_info::mutable_negative() {
  set_has_negative();
  if (negative_ == &::google::protobuf::internal::kEmptyString) {
    negative_ = new ::std::string;
  }
  return negative_;
}
inline ::std::string* unit_info::release_negative() {
  clear_has_negative();
  if (negative_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = negative_;
    negative_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional bytes exactnegative = 7;
inline bool unit_info::has_exactnegative() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void unit_info::set_has_exactnegative() {
  _has_bits_[0] |= 0x00000040u;
}
inline void unit_info::clear_has_exactnegative() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void unit_info::clear_exactnegative() {
  if (exactnegative_ != &::google::protobuf::internal::kEmptyString) {
    exactnegative_->clear();
  }
  clear_has_exactnegative();
}
inline const ::std::string& unit_info::exactnegative() const {
  return *exactnegative_;
}
inline void unit_info::set_exactnegative(const ::std::string& value) {
  set_has_exactnegative();
  if (exactnegative_ == &::google::protobuf::internal::kEmptyString) {
    exactnegative_ = new ::std::string;
  }
  exactnegative_->assign(value);
}
inline void unit_info::set_exactnegative(const char* value) {
  set_has_exactnegative();
  if (exactnegative_ == &::google::protobuf::internal::kEmptyString) {
    exactnegative_ = new ::std::string;
  }
  exactnegative_->assign(value);
}
inline void unit_info::set_exactnegative(const void* value, size_t size) {
  set_has_exactnegative();
  if (exactnegative_ == &::google::protobuf::internal::kEmptyString) {
    exactnegative_ = new ::std::string;
  }
  exactnegative_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* unit_info::mutable_exactnegative() {
  set_has_exactnegative();
  if (exactnegative_ == &::google::protobuf::internal::kEmptyString) {
    exactnegative_ = new ::std::string;
  }
  return exactnegative_;
}
inline ::std::string* unit_info::release_exactnegative() {
  clear_has_exactnegative();
  if (exactnegative_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = exactnegative_;
    exactnegative_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required bytes name = 8;
inline bool unit_info::has_name() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void unit_info::set_has_name() {
  _has_bits_[0] |= 0x00000080u;
}
inline void unit_info::clear_has_name() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void unit_info::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& unit_info::name() const {
  return *name_;
}
inline void unit_info::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void unit_info::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void unit_info::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* unit_info::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* unit_info::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required bytes cdate = 9;
inline bool unit_info::has_cdate() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void unit_info::set_has_cdate() {
  _has_bits_[0] |= 0x00000100u;
}
inline void unit_info::clear_has_cdate() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void unit_info::clear_cdate() {
  if (cdate_ != &::google::protobuf::internal::kEmptyString) {
    cdate_->clear();
  }
  clear_has_cdate();
}
inline const ::std::string& unit_info::cdate() const {
  return *cdate_;
}
inline void unit_info::set_cdate(const ::std::string& value) {
  set_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    cdate_ = new ::std::string;
  }
  cdate_->assign(value);
}
inline void unit_info::set_cdate(const char* value) {
  set_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    cdate_ = new ::std::string;
  }
  cdate_->assign(value);
}
inline void unit_info::set_cdate(const void* value, size_t size) {
  set_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    cdate_ = new ::std::string;
  }
  cdate_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* unit_info::mutable_cdate() {
  set_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    cdate_ = new ::std::string;
  }
  return cdate_;
}
inline ::std::string* unit_info::release_cdate() {
  clear_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = cdate_;
    cdate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required bytes udate = 10;
inline bool unit_info::has_udate() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void unit_info::set_has_udate() {
  _has_bits_[0] |= 0x00000200u;
}
inline void unit_info::clear_has_udate() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void unit_info::clear_udate() {
  if (udate_ != &::google::protobuf::internal::kEmptyString) {
    udate_->clear();
  }
  clear_has_udate();
}
inline const ::std::string& unit_info::udate() const {
  return *udate_;
}
inline void unit_info::set_udate(const ::std::string& value) {
  set_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    udate_ = new ::std::string;
  }
  udate_->assign(value);
}
inline void unit_info::set_udate(const char* value) {
  set_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    udate_ = new ::std::string;
  }
  udate_->assign(value);
}
inline void unit_info::set_udate(const void* value, size_t size) {
  set_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    udate_ = new ::std::string;
  }
  udate_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* unit_info::mutable_udate() {
  set_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    udate_ = new ::std::string;
  }
  return udate_;
}
inline ::std::string* unit_info::release_udate() {
  clear_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = udate_;
    udate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rtb
}  // namespace ad

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_unit_5finfo_2eproto__INCLUDED
