// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "unit_idea.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ad {
namespace rtb {

namespace {

const ::google::protobuf::Descriptor* unit_idea_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  unit_idea_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_unit_5fidea_2eproto() {
  protobuf_AddDesc_unit_5fidea_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "unit_idea.proto");
  GOOGLE_CHECK(file != NULL);
  unit_idea_descriptor_ = file->message_type(0);
  static const int unit_idea_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(unit_idea, unitid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(unit_idea, ideaid_),
  };
  unit_idea_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      unit_idea_descriptor_,
      unit_idea::default_instance_,
      unit_idea_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(unit_idea, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(unit_idea, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(unit_idea));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_unit_5fidea_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    unit_idea_descriptor_, &unit_idea::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_unit_5fidea_2eproto() {
  delete unit_idea::default_instance_;
  delete unit_idea_reflection_;
}

void protobuf_AddDesc_unit_5fidea_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::xbuiltin::protobuf_AddDesc_xbuiltin_2doptions_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017unit_idea.proto\022\006ad.rtb\032\026xbuiltin-opti"
    "ons.proto\"6\n\tunit_idea\022\016\n\006unitid\030\001 \002(\004\022\016"
    "\n\006ideaid\030\002 \003(\004:\t\322>\006unitid", 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "unit_idea.proto", &protobuf_RegisterTypes);
  unit_idea::default_instance_ = new unit_idea();
  unit_idea::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_unit_5fidea_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_unit_5fidea_2eproto {
  StaticDescriptorInitializer_unit_5fidea_2eproto() {
    protobuf_AddDesc_unit_5fidea_2eproto();
  }
} static_descriptor_initializer_unit_5fidea_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int unit_idea::kUnitidFieldNumber;
const int unit_idea::kIdeaidFieldNumber;
#endif  // !_MSC_VER

unit_idea::unit_idea()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void unit_idea::InitAsDefaultInstance() {
}

unit_idea::unit_idea(const unit_idea& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void unit_idea::SharedCtor() {
  _cached_size_ = 0;
  unitid_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

unit_idea::~unit_idea() {
  SharedDtor();
}

void unit_idea::SharedDtor() {
  if (this != default_instance_) {
  }
}

void unit_idea::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* unit_idea::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return unit_idea_descriptor_;
}

const unit_idea& unit_idea::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_unit_5fidea_2eproto();  return *default_instance_;
}

unit_idea* unit_idea::default_instance_ = NULL;

unit_idea* unit_idea::New() const {
  return new unit_idea;
}

void unit_idea::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    unitid_ = GOOGLE_ULONGLONG(0);
  }
  ideaid_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool unit_idea::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 unitid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &unitid_)));
          set_has_unitid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_ideaid;
        break;
      }
      
      // repeated uint64 ideaid = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_ideaid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 16, input, this->mutable_ideaid())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_ideaid())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_ideaid;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void unit_idea::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint64 unitid = 1;
  if (has_unitid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->unitid(), output);
  }
  
  // repeated uint64 ideaid = 2;
  for (int i = 0; i < this->ideaid_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      2, this->ideaid(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* unit_idea::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint64 unitid = 1;
  if (has_unitid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->unitid(), target);
  }
  
  // repeated uint64 ideaid = 2;
  for (int i = 0; i < this->ideaid_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt64ToArray(2, this->ideaid(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int unit_idea::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 unitid = 1;
    if (has_unitid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->unitid());
    }
    
  }
  // repeated uint64 ideaid = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->ideaid_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt64Size(this->ideaid(i));
    }
    total_size += 1 * this->ideaid_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void unit_idea::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const unit_idea* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const unit_idea*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void unit_idea::MergeFrom(const unit_idea& from) {
  GOOGLE_CHECK_NE(&from, this);
  ideaid_.MergeFrom(from.ideaid_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_unitid()) {
      set_unitid(from.unitid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void unit_idea::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void unit_idea::CopyFrom(const unit_idea& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool unit_idea::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void unit_idea::Swap(unit_idea* other) {
  if (other != this) {
    std::swap(unitid_, other->unitid_);
    ideaid_.Swap(&other->ideaid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata unit_idea::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = unit_idea_descriptor_;
  metadata.reflection = unit_idea_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rtb
}  // namespace ad

// @@protoc_insertion_point(global_scope)
