// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_info.proto

#ifndef PROTOBUF_user_5finfo_2eproto__INCLUDED
#define PROTOBUF_user_5finfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "xbuiltin-options.pb.h"
#include <xbuiltin/Utils.h>
// @@protoc_insertion_point(includes)

namespace ad {
namespace rtb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_user_5finfo_2eproto();
void protobuf_AssignDesc_user_5finfo_2eproto();
void protobuf_ShutdownFile_user_5finfo_2eproto();

class user_info;

// ===================================================================

class user_info : public ::google::protobuf::Message {
 public:
  user_info();
  virtual ~user_info();
  
  user_info(const user_info& from);
  
  inline user_info& operator=(const user_info& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const user_info& default_instance();
  
  void Swap(user_info* other);
  
  // implements Message ----------------------------------------------
  
  user_info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const user_info& from);
  void MergeFrom(const user_info& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint64 level = 1;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 1;
  inline ::google::protobuf::uint64 level() const;
  inline void set_level(::google::protobuf::uint64 value);
  
  // required uint64 userid = 2;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUseridFieldNumber = 2;
  inline ::google::protobuf::uint64 userid() const;
  inline void set_userid(::google::protobuf::uint64 value);
  
  // required uint64 ustatid = 3;
  inline bool has_ustatid() const;
  inline void clear_ustatid();
  static const int kUstatidFieldNumber = 3;
  inline ::google::protobuf::uint64 ustatid() const;
  inline void set_ustatid(::google::protobuf::uint64 value);
  
  // required bytes ipblack = 4;
  inline bool has_ipblack() const;
  inline void clear_ipblack();
  static const int kIpblackFieldNumber = 4;
  inline const ::std::string& ipblack() const;
  inline void set_ipblack(const ::std::string& value);
  inline void set_ipblack(const char* value);
  inline void set_ipblack(const void* value, size_t size);
  inline ::std::string* mutable_ipblack();
  inline ::std::string* release_ipblack();
  
  // required bytes region = 5;
  inline bool has_region() const;
  inline void clear_region();
  static const int kRegionFieldNumber = 5;
  inline const ::std::string& region() const;
  inline void set_region(const ::std::string& value);
  inline void set_region(const char* value);
  inline void set_region(const void* value, size_t size);
  inline ::std::string* mutable_region();
  inline ::std::string* release_region();
  
  // required uint64 budget = 6;
  inline bool has_budget() const;
  inline void clear_budget();
  static const int kBudgetFieldNumber = 6;
  inline ::google::protobuf::uint64 budget() const;
  inline void set_budget(::google::protobuf::uint64 value);
  
  // required uint64 budget_all = 7;
  inline bool has_budget_all() const;
  inline void clear_budget_all();
  static const int kBudgetAllFieldNumber = 7;
  inline ::google::protobuf::uint64 budget_all() const;
  inline void set_budget_all(::google::protobuf::uint64 value);
  
  // required uint64 consume = 8;
  inline bool has_consume() const;
  inline void clear_consume();
  static const int kConsumeFieldNumber = 8;
  inline ::google::protobuf::uint64 consume() const;
  inline void set_consume(::google::protobuf::uint64 value);
  
  // required uint64 consume_all = 9;
  inline bool has_consume_all() const;
  inline void clear_consume_all();
  static const int kConsumeAllFieldNumber = 9;
  inline ::google::protobuf::uint64 consume_all() const;
  inline void set_consume_all(::google::protobuf::uint64 value);
  
  // required bytes name = 10;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 10;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const void* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // required bytes cdate = 11;
  inline bool has_cdate() const;
  inline void clear_cdate();
  static const int kCdateFieldNumber = 11;
  inline const ::std::string& cdate() const;
  inline void set_cdate(const ::std::string& value);
  inline void set_cdate(const char* value);
  inline void set_cdate(const void* value, size_t size);
  inline ::std::string* mutable_cdate();
  inline ::std::string* release_cdate();
  
  // required bytes udate = 12;
  inline bool has_udate() const;
  inline void clear_udate();
  static const int kUdateFieldNumber = 12;
  inline const ::std::string& udate() const;
  inline void set_udate(const ::std::string& value);
  inline void set_udate(const char* value);
  inline void set_udate(const void* value, size_t size);
  inline ::std::string* mutable_udate();
  inline ::std::string* release_udate();
  
  static inline int generate_keysign(const uint64_t xdict_userid, uint64_t *output) {
    if (::xbuiltin::make_sign64(xdict_userid, output) < 0) {
      return -1;
    }
    return 0;
  }
  int generate_keysign(uint64_t *output) {
    return generate_keysign(userid(), output);
  }
  void clear_optionals() {
  }
  int load_tsl(char *&str) {
    // level
    uint64_t xdict_level_value;
    if (::xbuiltin::xconvert(str, &xdict_level_value) < 0) {
      return -1;
    }
    set_level(xdict_level_value);
    // userid
    uint64_t xdict_userid_value;
    if (::xbuiltin::xconvert(str, &xdict_userid_value) < 0) {
      return -1;
    }
    set_userid(xdict_userid_value);
    // ustatid
    uint64_t xdict_ustatid_value;
    if (::xbuiltin::xconvert(str, &xdict_ustatid_value) < 0) {
      return -1;
    }
    set_ustatid(xdict_ustatid_value);
    // ipblack
    char * xdict_ipblack_value;
    if (::xbuiltin::xconvert(str, &xdict_ipblack_value) < 0) {
      return -1;
    }
    set_ipblack(xdict_ipblack_value);
    // region
    char * xdict_region_value;
    if (::xbuiltin::xconvert(str, &xdict_region_value) < 0) {
      return -1;
    }
    set_region(xdict_region_value);
    // budget
    uint64_t xdict_budget_value;
    if (::xbuiltin::xconvert(str, &xdict_budget_value) < 0) {
      return -1;
    }
    set_budget(xdict_budget_value);
    // budget_all
    uint64_t xdict_budget_all_value;
    if (::xbuiltin::xconvert(str, &xdict_budget_all_value) < 0) {
      return -1;
    }
    set_budget_all(xdict_budget_all_value);
    // consume
    uint64_t xdict_consume_value;
    if (::xbuiltin::xconvert(str, &xdict_consume_value) < 0) {
      return -1;
    }
    set_consume(xdict_consume_value);
    // consume_all
    uint64_t xdict_consume_all_value;
    if (::xbuiltin::xconvert(str, &xdict_consume_all_value) < 0) {
      return -1;
    }
    set_consume_all(xdict_consume_all_value);
    // name
    char * xdict_name_value;
    if (::xbuiltin::xconvert(str, &xdict_name_value) < 0) {
      return -1;
    }
    set_name(xdict_name_value);
    // cdate
    char * xdict_cdate_value;
    if (::xbuiltin::xconvert(str, &xdict_cdate_value) < 0) {
      return -1;
    }
    set_cdate(xdict_cdate_value);
    // udate
    char * xdict_udate_value;
    if (::xbuiltin::xconvert(str, &xdict_udate_value) < 0) {
      return -1;
    }
    set_udate(xdict_udate_value);
    return 0;
  }
  // @@protoc_insertion_point(class_scope:ad.rtb.user_info)
 private:
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_ustatid();
  inline void clear_has_ustatid();
  inline void set_has_ipblack();
  inline void clear_has_ipblack();
  inline void set_has_region();
  inline void clear_has_region();
  inline void set_has_budget();
  inline void clear_has_budget();
  inline void set_has_budget_all();
  inline void clear_has_budget_all();
  inline void set_has_consume();
  inline void clear_has_consume();
  inline void set_has_consume_all();
  inline void clear_has_consume_all();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_cdate();
  inline void clear_has_cdate();
  inline void set_has_udate();
  inline void clear_has_udate();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 level_;
  ::google::protobuf::uint64 userid_;
  ::google::protobuf::uint64 ustatid_;
  ::std::string* ipblack_;
  ::std::string* region_;
  ::google::protobuf::uint64 budget_;
  ::google::protobuf::uint64 budget_all_;
  ::google::protobuf::uint64 consume_;
  ::google::protobuf::uint64 consume_all_;
  ::std::string* name_;
  ::std::string* cdate_;
  ::std::string* udate_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(12 + 31) / 32];
  
  friend void  protobuf_AddDesc_user_5finfo_2eproto();
  friend void protobuf_AssignDesc_user_5finfo_2eproto();
  friend void protobuf_ShutdownFile_user_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static user_info* default_instance_;
};
// ===================================================================


// ===================================================================

// user_info

// optional uint64 level = 1;
inline bool user_info::has_level() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void user_info::set_has_level() {
  _has_bits_[0] |= 0x00000001u;
}
inline void user_info::clear_has_level() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void user_info::clear_level() {
  level_ = GOOGLE_ULONGLONG(0);
  clear_has_level();
}
inline ::google::protobuf::uint64 user_info::level() const {
  return level_;
}
inline void user_info::set_level(::google::protobuf::uint64 value) {
  set_has_level();
  level_ = value;
}

// required uint64 userid = 2;
inline bool user_info::has_userid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void user_info::set_has_userid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void user_info::clear_has_userid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void user_info::clear_userid() {
  userid_ = GOOGLE_ULONGLONG(0);
  clear_has_userid();
}
inline ::google::protobuf::uint64 user_info::userid() const {
  return userid_;
}
inline void user_info::set_userid(::google::protobuf::uint64 value) {
  set_has_userid();
  userid_ = value;
}

// required uint64 ustatid = 3;
inline bool user_info::has_ustatid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void user_info::set_has_ustatid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void user_info::clear_has_ustatid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void user_info::clear_ustatid() {
  ustatid_ = GOOGLE_ULONGLONG(0);
  clear_has_ustatid();
}
inline ::google::protobuf::uint64 user_info::ustatid() const {
  return ustatid_;
}
inline void user_info::set_ustatid(::google::protobuf::uint64 value) {
  set_has_ustatid();
  ustatid_ = value;
}

// required bytes ipblack = 4;
inline bool user_info::has_ipblack() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void user_info::set_has_ipblack() {
  _has_bits_[0] |= 0x00000008u;
}
inline void user_info::clear_has_ipblack() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void user_info::clear_ipblack() {
  if (ipblack_ != &::google::protobuf::internal::kEmptyString) {
    ipblack_->clear();
  }
  clear_has_ipblack();
}
inline const ::std::string& user_info::ipblack() const {
  return *ipblack_;
}
inline void user_info::set_ipblack(const ::std::string& value) {
  set_has_ipblack();
  if (ipblack_ == &::google::protobuf::internal::kEmptyString) {
    ipblack_ = new ::std::string;
  }
  ipblack_->assign(value);
}
inline void user_info::set_ipblack(const char* value) {
  set_has_ipblack();
  if (ipblack_ == &::google::protobuf::internal::kEmptyString) {
    ipblack_ = new ::std::string;
  }
  ipblack_->assign(value);
}
inline void user_info::set_ipblack(const void* value, size_t size) {
  set_has_ipblack();
  if (ipblack_ == &::google::protobuf::internal::kEmptyString) {
    ipblack_ = new ::std::string;
  }
  ipblack_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* user_info::mutable_ipblack() {
  set_has_ipblack();
  if (ipblack_ == &::google::protobuf::internal::kEmptyString) {
    ipblack_ = new ::std::string;
  }
  return ipblack_;
}
inline ::std::string* user_info::release_ipblack() {
  clear_has_ipblack();
  if (ipblack_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ipblack_;
    ipblack_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required bytes region = 5;
inline bool user_info::has_region() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void user_info::set_has_region() {
  _has_bits_[0] |= 0x00000010u;
}
inline void user_info::clear_has_region() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void user_info::clear_region() {
  if (region_ != &::google::protobuf::internal::kEmptyString) {
    region_->clear();
  }
  clear_has_region();
}
inline const ::std::string& user_info::region() const {
  return *region_;
}
inline void user_info::set_region(const ::std::string& value) {
  set_has_region();
  if (region_ == &::google::protobuf::internal::kEmptyString) {
    region_ = new ::std::string;
  }
  region_->assign(value);
}
inline void user_info::set_region(const char* value) {
  set_has_region();
  if (region_ == &::google::protobuf::internal::kEmptyString) {
    region_ = new ::std::string;
  }
  region_->assign(value);
}
inline void user_info::set_region(const void* value, size_t size) {
  set_has_region();
  if (region_ == &::google::protobuf::internal::kEmptyString) {
    region_ = new ::std::string;
  }
  region_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* user_info::mutable_region() {
  set_has_region();
  if (region_ == &::google::protobuf::internal::kEmptyString) {
    region_ = new ::std::string;
  }
  return region_;
}
inline ::std::string* user_info::release_region() {
  clear_has_region();
  if (region_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = region_;
    region_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint64 budget = 6;
inline bool user_info::has_budget() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void user_info::set_has_budget() {
  _has_bits_[0] |= 0x00000020u;
}
inline void user_info::clear_has_budget() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void user_info::clear_budget() {
  budget_ = GOOGLE_ULONGLONG(0);
  clear_has_budget();
}
inline ::google::protobuf::uint64 user_info::budget() const {
  return budget_;
}
inline void user_info::set_budget(::google::protobuf::uint64 value) {
  set_has_budget();
  budget_ = value;
}

// required uint64 budget_all = 7;
inline bool user_info::has_budget_all() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void user_info::set_has_budget_all() {
  _has_bits_[0] |= 0x00000040u;
}
inline void user_info::clear_has_budget_all() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void user_info::clear_budget_all() {
  budget_all_ = GOOGLE_ULONGLONG(0);
  clear_has_budget_all();
}
inline ::google::protobuf::uint64 user_info::budget_all() const {
  return budget_all_;
}
inline void user_info::set_budget_all(::google::protobuf::uint64 value) {
  set_has_budget_all();
  budget_all_ = value;
}

// required uint64 consume = 8;
inline bool user_info::has_consume() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void user_info::set_has_consume() {
  _has_bits_[0] |= 0x00000080u;
}
inline void user_info::clear_has_consume() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void user_info::clear_consume() {
  consume_ = GOOGLE_ULONGLONG(0);
  clear_has_consume();
}
inline ::google::protobuf::uint64 user_info::consume() const {
  return consume_;
}
inline void user_info::set_consume(::google::protobuf::uint64 value) {
  set_has_consume();
  consume_ = value;
}

// required uint64 consume_all = 9;
inline bool user_info::has_consume_all() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void user_info::set_has_consume_all() {
  _has_bits_[0] |= 0x00000100u;
}
inline void user_info::clear_has_consume_all() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void user_info::clear_consume_all() {
  consume_all_ = GOOGLE_ULONGLONG(0);
  clear_has_consume_all();
}
inline ::google::protobuf::uint64 user_info::consume_all() const {
  return consume_all_;
}
inline void user_info::set_consume_all(::google::protobuf::uint64 value) {
  set_has_consume_all();
  consume_all_ = value;
}

// required bytes name = 10;
inline bool user_info::has_name() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void user_info::set_has_name() {
  _has_bits_[0] |= 0x00000200u;
}
inline void user_info::clear_has_name() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void user_info::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& user_info::name() const {
  return *name_;
}
inline void user_info::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void user_info::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void user_info::set_name(const void* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* user_info::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* user_info::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required bytes cdate = 11;
inline bool user_info::has_cdate() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void user_info::set_has_cdate() {
  _has_bits_[0] |= 0x00000400u;
}
inline void user_info::clear_has_cdate() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void user_info::clear_cdate() {
  if (cdate_ != &::google::protobuf::internal::kEmptyString) {
    cdate_->clear();
  }
  clear_has_cdate();
}
inline const ::std::string& user_info::cdate() const {
  return *cdate_;
}
inline void user_info::set_cdate(const ::std::string& value) {
  set_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    cdate_ = new ::std::string;
  }
  cdate_->assign(value);
}
inline void user_info::set_cdate(const char* value) {
  set_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    cdate_ = new ::std::string;
  }
  cdate_->assign(value);
}
inline void user_info::set_cdate(const void* value, size_t size) {
  set_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    cdate_ = new ::std::string;
  }
  cdate_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* user_info::mutable_cdate() {
  set_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    cdate_ = new ::std::string;
  }
  return cdate_;
}
inline ::std::string* user_info::release_cdate() {
  clear_has_cdate();
  if (cdate_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = cdate_;
    cdate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required bytes udate = 12;
inline bool user_info::has_udate() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void user_info::set_has_udate() {
  _has_bits_[0] |= 0x00000800u;
}
inline void user_info::clear_has_udate() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void user_info::clear_udate() {
  if (udate_ != &::google::protobuf::internal::kEmptyString) {
    udate_->clear();
  }
  clear_has_udate();
}
inline const ::std::string& user_info::udate() const {
  return *udate_;
}
inline void user_info::set_udate(const ::std::string& value) {
  set_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    udate_ = new ::std::string;
  }
  udate_->assign(value);
}
inline void user_info::set_udate(const char* value) {
  set_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    udate_ = new ::std::string;
  }
  udate_->assign(value);
}
inline void user_info::set_udate(const void* value, size_t size) {
  set_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    udate_ = new ::std::string;
  }
  udate_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* user_info::mutable_udate() {
  set_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    udate_ = new ::std::string;
  }
  return udate_;
}
inline ::std::string* user_info::release_udate() {
  clear_has_udate();
  if (udate_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = udate_;
    udate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rtb
}  // namespace ad

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_user_5finfo_2eproto__INCLUDED
